### ISSUE TITLE
No SR file after the analysis

### ISSUE THREAD

**Issue by mfmonreal** [Rizzoli-Lab/ONE-Microscopy-Java-Plugin#1]
I've followed the installing instructions from your site, I removed old pluggins and .jars and installed your ONE platform (FIJI version v1.54k). Everything looks normal and when I tried to apply the plugging in my data (proExM 4x, lattice light sheet microscopy acquisition, 863 frames) the screens of my computer shut off and on and I got the message of computer ended. However, in the created folder I do not have any reconstruction or high resolution image, the ONE folder is empty and I get the drift table and this exception:

(Fiji Is Just) ImageJ 2.14.0/1.54k; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 310MB of 50000MB (<1%)
 
java.lang.AssertionError: user supplied Device incompatible with current EXECUTION_MODE or getTargetDevice(); device = NVIDIA<GPU>; kernel = Kernel_SRRF, devices={Intel<GPU>|Java Alternative Algorithm|Java Thread Pool}
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1532)
	at com.aparapi.internal.kernel.KernelRunner.fallBackToNextDevice(KernelRunner.java:1437)
	at com.aparapi.internal.kernel.KernelRunner.fallBackToNextDevice(KernelRunner.java:1398)
	at com.aparapi.internal.kernel.KernelRunner.executeOpenCL(KernelRunner.java:1333)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1868)
	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1471)
	at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1454)
	at com.aparapi.Kernel.execute(Kernel.java:2907)
	at com.aparapi.Kernel.execute(Kernel.java:2864)
	at com.aparapi.Kernel.execute(Kernel.java:2804)
	at nanoj.core.java.aparapi.NJKernel.execute(NJKernel.java:91)
	at nanoj.srrf.java.Kernel_SRRF.calculate(SRRF.java:215)
	at nanoj.srrf.java.SRRF.calculate(SRRF.java:83)
	at nanoj.srrf.java.SRRF.calculate(SRRF.java:96)
	at nanoj.srrf.java.gui.SRRFAnalysis_.runAnalysis(SRRFAnalysis_.java:378)
	at nanoj.srrf.java.gui.SRRFAnalysis_.execute(SRRFAnalysis_.java:243)
	at nanoj.core.java.gui._BaseDialog_.run(_BaseDialog_.java:118)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at ij.IJ.run(IJ.java:326)
	at ij.IJ.run(IJ.java:416)
	at com.ONEMicroscopy.StartONEanalysis.SRRFanalysis(StartONEanalysis.java:447)
	at com.ONEMicroscopy.StartONEanalysis.StartAnalysis(StartONEanalysis.java:324)
	at com.ONEMicroscopy.StartONEanalysis.runAnalysis(StartONEanalysis.java:203)
	at com.ONEMicroscopy.StartONEanalysis.run(StartONEanalysis.java:129)
	at com.ONEMicroscopy.gui.MainWindow$32$1.run(MainWindow.java:812)
	at java.lang.Thread.run(Thread.java:748)

[Log file.txt](https://github.com/user-attachments/files/17397764/Log.file.txt)

What did I do wrong?

Thank you,

M.

**Comment by WootaMelon** [comment]
Hello Mónica,

The error you received relates to issues with running the analysis on the GPU for acceleration. This means that the analysis failed and did not generate a SR file.

**After taking a look at the provided log file, the parameters you used for analysis were tested and worked fine.**

To be able to pinpoint the source of the problem, could you kindly provide us with the following:

1. **the dataset's width and height in pixels or, if possible, the dataset itself, that is not being super resolved**
2. **The name of the GPU you are using for analysis and its driver version**

Does the issue happen with a different dataset?

Based on your description of screens turning off, it is most likely an issue relating to GPU drivers and OpenCL compatibility. Screens should not restart when running the analysis. 

Things to try: 

1. **If you have old GPU drivers, you can try updating to newer drivers first.** 
2. **Check if you have the “OpenCL™, OpenGL®, and Vulkan® Compatibility Pack” installed.**

Thanks!

Mahdi
